"""empty message

Revision ID: 1a60f3053ee9
Revises: 
Create Date: 2018-08-19 23:42:15.499878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a60f3053ee9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all',
    sa.Column('all_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('good_num', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('all_id')
    )
    op.create_table('good',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('good_pic_url', sa.String(length=20), nullable=False),
    sa.Column('good_price', sa.String(length=20), nullable=False),
    sa.Column('good_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('good_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('good')
    op.drop_table('all')
    # ### end Alembic commands ###
