"""empty message

Revision ID: ebba50bdeaf6
Revises: 489d7a5acea7
Create Date: 2018-08-25 00:10:42.832958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebba50bdeaf6'
down_revision = '489d7a5acea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_name', table_name='order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_name', 'order', ['user_name'], unique=True)
    # ### end Alembic commands ###
